# akita conda runner uses the following image by default:
# image: continuumio/miniconda3:4.9.2

stages:
  - test
  - build
  - deploy

workflow:
  rules:
    # If `$FORCE_GITLAB_CI` is set, create a pipeline.
    - if: '$FORCE_GITLAB_CI'
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For `main` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'
    # For branches starting with 'doc/' don't create a pipeline
    - if: '$CI_COMMIT_BRANCH =~ /^doc\//'
      when: never

before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - echo "Setting up conda environment and installing dependencies"
  - conda env create -n testenv python=3.6.2
  - conda install -n testenv -c conda-forge gcc
  - source activate testenv

test:
  stage: test
  interruptible: true
  tags:
    - akita
    - conda
  before_script:
    - pip install $(python dependencies.py --tag test)
  script:
    - flake8
    - mypy
    - pytest

build:
  stage: build
  tags:
    - akita
    - conda
  only:
    - tags
  before_script:
    - pip install $(python dependencies.py --tag build)
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz

deploy:
  stage: deploy
  tags:
    - akita
    - conda
  only:
    - tags
  script:
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url https://gitlab.hpi.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
