name: Python build and test using Conda

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Build and test PyOnlineSVR on ${{ matrix.os }} with python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python_version: ["3.9"]  # ["3.6.10", "3.7", "3.8", "3.9"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        # auto-update-conda: true
        python-version: ${{ matrix.python_version }}
    - name: Install build dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        conda install -y swig gcc_linux-64 gxx_linux-64
    - name: Install build dependencies
      if: matrix.os == 'macOS-latest'
      run: |
        conda install -y swig clang_osx-64 clangxx_osx-64
    - name: Install test dependencies
      run: |
        pip install $(python dependencies.py --tag "${DEP_TAG:-test}" --no-pin)
    - name: Versions
      run: |
        python --version
        conda --version
        pip --version
        echo "flake8"; flake8 --version
        mypy --version
        pytest --version
    - name: Build extension and generate source files
      run: |
        python setup.py build_ext --inplace
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Typecheck with mypy
      run: |
        mypy
    - name: Test with pytest
      run: |
        pytest

  build-binary-wheel:
    name: Build binary wheel on ${{ matrix.os }} with python ${{ matrix.python_version }}
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python_version: ["3.6.10", "3.7", "3.8", "3.9"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda create -n testenv -y swig gcc_linux-64 gxx_linuxsource 64
        source activate testenv
        pip install $(python dependencies.py --tag "${DEP_TAG:-build}" --no-pin)
    - name: Build wheel
      run: |
        python setup.py bdist_wheel
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: packages-${{ matrix.os }}-${{ matrix.python_version }}
        path: dist

  build-source-distribution:
    name: Building source distribution with python ${{ matrix.python_version }}
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda create -n testenv -y swig gcc_linux-64 gxx_linux-64
        source activate testenv
        pip install $(python dependencies.py --tag "${DEP_TAG:-build}" --no-pin)
    - name: Build source distribution
      run: |
        python setup.py sdist
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: packages-source-${{ matrix.python_version }}
        path: dist

  publish:
    name: Publish distributions
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build-binary-wheel, build-source-distribution]
    runs-on: ubuntu-latest

    steps:
    - name: Download packages
      uses: actions/download-artifact@v2
      with:
        path: dist
    - name: Publish package to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
