name: Python build and test using Conda

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python_version: ["3.6.10", "3.7", "3.8", "3.9"]
      fail-fast: false

    name: Build and test PyOnlineSVR on ${{ matrix.os }} with python ${{ matrix.python_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -y swig gcc_linux-64 gxx_linux-64
        pip install $(python dependencies.py --tag "${DEP_TAG:-test}" --no-pin)
    - name: Versions
      run: |
        python --version
        conda --version
        pip --version
        flake8 --version
        mypy --version
        pytest --version
    - name: Build extension and generate source files
      run: |
        python setup.py build_ext --inplace
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Typecheck with mypy
      run: |
        mypy
    - name: Test with pytest
      run: |
        pytest
