name: Python Package using Conda

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, windows-latest, maxOS-latest]
        python_version: ["3.6.10", "3.7", "3.8", "3.9"]
    
    name: Build and test PyOnlineSVR on ${{ matrix.os }} with python ${{ matrix.python_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -n pyonlinesvr -y swig gcc_linux-64 gxx_linux-64
        pip install $(python dependencies.py --tag "${DEP_TAG:-test}" --no-pin)
    - name: Build extension and generate source files
      run: |
        python setup.py build_ext --inplace
    - name: Lint with flake8 and mypy
      run: |
        flake8 . --count --show-source --statistics
        mypy .
    - name: Test with pytest
      run: |
        pytest .
